### ISSUE TITLE
Notenames shifted by an octave

### ISSUE THREAD

**Issue by johannes-mueller** [wmedrano/wmidi#22]
The note names i.e. variants of the `Note` enum differ from the usual naming by an octave.

The usual name for the lowest key on a grand piano (MIDI note 21) is 'A0', whereas in `wmidi::Note` the variant is `AMinus1`. The `A0` in `wmidi::Note` is MIDI note 33, one octave higher, which usually is referred to as 'A1'.

Why is that?

It's a bit confusing when developing with wmidi that the wmidi names are always shifted by an octave.

Sources:
https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies
https://newt.phys.unsw.edu.au/jw/notes.html
...

**Comment by wmedrano** [comment]
Not sure where I got my spec from, but this does seem to be the more popular one. This should be fixed by the next breaking version which would be 4.0

**Comment by wmedrano** [comment]
This is live in the 4.0.0 release.
